# docker compose for system required services

services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Abcd@12345
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
  
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
  redis:
    image: redis
